name: CI

on:
  push:
    branches: ['main']
  pull_request:

permissions:
  pull-requests: write

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Comment preparing to deploy
        if: ${{ github.event_name != 'push' }}
        uses: mshick/add-pr-comment@v2
        with:
          message-id: cloudflare-pages-preview-deployment
          message: |
            ## <span aria-hidden="true">🚧</span> Preparing to Deploy Preview...

            | Name | Link |
            | ---- | ---- |
            | **Latest commit** | ${{ github.sha }} |

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.0

      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Check code format
        run: pnpm format:check

      - name: Linting
        run: pnpm lint

      - name: Check type
        run: pnpm type:check

      - name: Build
        run: pnpm build
